version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      SELENUM_REMOTE_URL: http://selenium-chrome:4444
      WEBPACKER_DEV_SERVER_HOST: webpack-dev-server
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack-dev-server
      - selenium-chrome

  webpack-dev-server:
    build: .
    command: bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle

  selenium-chrome:
    image: seleniarm/standalone-chromium:4.0.0-beta-1-20210215
    shm_size: 2gb
    ports:
      - "4444:4444"

volumes:
  db_data:
  bundle:
